### ISSUE TITLE
Prijedlog poveznice na pravu sliku u README.md

### ISSUE THREAD

**Issue by sbravar** [SolderedElectronics/Soldered-PCF85063A-RTC-Module-Arduino-Library#2]
https://github.com/SolderedElectronics/Soldered-PCF85063A-RTC-Module-Arduino-Library/blob/4e63bbe47d73c2c9f0efe961f6d7939e5f0c03ce/README.md?plain=1#L7C41-L7C110

umjesto:

https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg

čini mi se da bi moglo biti:

https://github.com/SolderedElectronics/Real-time-clock-RTC-PCF85063A-breakout-hardware-design/blob/main/OUTPUTS/V1.2.2/333051.jpg?raw=true

**Comment by rsoric** [comment]
Hello, and thank you for your feedback. We are currently working on automating this process. Soon, all repositories will be updated with the real content. Cheers!
